import{connect as _a}from'cloudflare:sockets';
const _b=75;
const _d=__WORKER_TOKEN_ARRAY__;
const _e=(()=>_d.map(v=>String.fromCharCode(v^_b)).join('').replace(/-/g,'').toLowerCase())();
const _PF=['[2602:fc59:b0:64::]','[2602:fc59:11:64::]','[2a02:898:146:64::]'];
export default{async fetch(r,env){if((r.headers.get('upgrade')||'').toLowerCase()!=='websocket')return new Response('',{status:200});return _ws(r,env?.PROXYIP||'')}};
function _ded(h){if(!h)return null;try{return Uint8Array.from(atob(h.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0)).buffer}catch(_){return null}}
function _stream(ws,ed){return new ReadableStream({start(ctrl){if(ed)ctrl.enqueue(ed);ws.addEventListener('message',({data:m})=>ctrl.enqueue(m));ws.addEventListener('close',()=>ctrl.close());ws.addEventListener('error',e=>ctrl.error(e))}})}
async function _rdns(h){try{const r=await fetch('https://cloudflare-dns.com/dns-query?name='+encodeURIComponent(h)+'&type=A',{headers:{accept:'application/dns-json'}});const d=await r.json();return d.Answer?.find(a=>a.type===1)?.data||null}catch(_){return null}}
function _pfx(ipv4,p){const h=ipv4.split('.').map(n=>parseInt(n).toString(16).padStart(2,'0'));const m=p.match(/^\[([0-9A-Fa-f:]+)\]$/);return m?`[${m[1]}${h[0]}${h[1]}:${h[2]}${h[3]}]`:null}
async function _conn(host,port,init,proxy){const _try=async(h)=>{const s=_a({hostname:h,port});if(init.byteLength>0){const w=s.writable.getWriter();await w.write(init);w.releaseLock()}return s};try{return await _try(host)}catch(_){}if(proxy){try{return await _try(proxy)}catch(_){}}const isv4=/^(\d{1,3}\.){3}\d{1,3}$/.test(host);const v4=isv4?host:await _rdns(host);if(v4){const p=_PF[Math.floor(Math.random()*_PF.length)];const v6=_pfx(v4,p);if(v6){try{return await _try(v6)}catch(_){}}}throw new Error('failed')}
async function _ws(r,proxy){const[cl,sv]=Object.values(new WebSocketPair());sv.accept();sv.binaryType='arraybuffer';const ed=_ded(r.headers.get('sec-websocket-protocol')||'');let sock=null;_stream(sv,ed).pipeTo(new WritableStream({async write(chunk){if(sock){const w=sock.writable.getWriter();await w.write(chunk);w.releaseLock();return}const d=chunk instanceof ArrayBuffer?new Uint8Array(chunk):new Uint8Array(await chunk.arrayBuffer());if(d.length<19)throw new Error('short');const uid=[...d.slice(1,17)].map(v=>v.toString(16).padStart(2,'0')).join('');if(uid!==_e)throw new Error('auth');const al=d[17];let i=18+al+1;const port=(d[i]<<8)|d[i+1];i+=2;const at=d[i++];let host='';if(at===1){host=[...d.slice(i,i+4)].join('.');i+=4}else if(at===2){const n=d[i++];host=new TextDecoder().decode(d.slice(i,i+n));i+=n}else if(at===3){const b=d.slice(i,i+16);host=[...Array(8)].map((_,j)=>((b[j*2]<<8)|b[j*2+1]).toString(16)).join(':');i+=16}else throw new Error('atype');const init=d.slice(i);sv.send(new Uint8Array([0,0]));sock=await _conn(host,port,init,proxy);(async()=>{try{const rd=sock.readable.getReader();for(;;){const{done,value}=await rd.read();if(done)break;sv.send(value)}}catch(_){}try{sv.close()}catch(_){}})()},close(){try{sock?.readable.cancel()}catch(_){}},abort(){try{sock?.readable.cancel()}catch(_){}}})).catch(()=>{});return new Response(null,{status:101,webSocket:cl})}